services:
  hw-pulse-redis:
    image: redis:7
    container_name: hw-pulse-redis
    restart: always
    depends_on:
      - hw-pulse-postgres
    networks:
      - hw-pulse-network

  hw-pulse-postgres:
    image: postgres:15-alpine
    container_name: hw-pulse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - hw-pulse-network

  hw-pulse-api:
    container_name: hw-pulse-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      REDIS_HOST: hw-pulse-redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - hw-pulse-redis
    networks:
      - hw-pulse-network

  hw-pulse-migrations:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DB_HOST: hw-pulse-postgres
      DB_PORT: ${DB_PORT} 
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME} 
    command: poetry run alembic upgrade head
    depends_on:
      - hw-pulse-postgres
    networks:
      - hw-pulse-network

  hw-pulse-bot:
    container_name: hw-pulse-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      REDIS_HOST: hw-pulse-redis
      REDIS_PORT: 6379
      BOT_TOKEN: ${BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - hw-pulse-redis
      - hw-pulse-api
    networks:
      - hw-pulse-network

networks:
  hw-pulse-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data
