FROM python:3.14

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-root --only main

COPY src/api /app/src/api

ENV PYTHONPATH=/app/src
CMD ["python", "-m", "api"]