[project]
name = "hw-pulse"
version = "0.1.0"
description = ""
authors = [
    {name = "ksredkin",email = "ksredkin0968@gmail.com"}
]
requires-python = ">=3.14,<3.15"
dependencies = [
    "psutil (>=7.2.2,<8.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "fastapi (>=0.136.1,<0.137.0)",
    "uvicorn (>=0.47.0,<0.48.0)",
    "redis (>=7.4.0,<8.0.0)",
    "aiogram (>=3.28.2,<4.0.0)",
    "singbox2proxy (>=0.3.4,<0.4.0)",
    "aiohttp-socks (>=0.11.0,<0.12.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "sqlalchemy[asyncio] (>=2.0.49,<3.0.0)",
    "alembic (>=1.18.4,<2.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "psycopg2 (>=2.9.12,<3.0.0)"
]

[tool.poetry]
package-mode = false

[tool.mypy]
python_version = 3.14
ignore_missing_imports = true
disallow_untyped_defs = true
strict = true

[tool.ruff]
line-length = 88
target-version = "py314"
exclude = ["venv", "versions"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy (>=2.1.0,<3.0.0)",
    "ruff (>=0.15.13,<0.16.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "fakeredis (>=2.35.1,<3.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "pytest-coverage (>=0.0,<0.1)"
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
