"""add alert settings to the users table

Revision ID: 86537e7c5631
Revises: 89c8a0f47b71
Create Date: 2026-05-25 15:40:22.735304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86537e7c5631'
down_revision: Union[str, Sequence[str], None] = '89c8a0f47b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alert_enabled', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('alert_temp', sa.Integer(), nullable=True, default=80))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alert_temp')
    op.drop_column('users', 'alert_enabled')
    # ### end Alembic commands ###
